apiVersion: v1
kind: List
items:
  # -------- DEV ------------------------------------------------------
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: devistor-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:VipInformatique/k3s-gitops-infra.git
        path: apps/devistor-app/releases/dev
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

  # -------- PROD -----------------------------------------------------
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: devistor-prod
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: git@github.com:VipInformatique/k3s-gitops-infra.git
        path: apps/devistor-app/releases/prod
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true