apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"canary-pvc","namespace":"prod-restore"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"100Mi"}},"storageClassName":"local-path"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k8s-master-02
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2025-08-13T16:34:28Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: canary-pvc
  namespace: prod-restore
  resourceVersion: "9727170"
  uid: e127591e-d1f4-41f0-93fa-788a8ff8acc8
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-e127591e-d1f4-41f0-93fa-788a8ff8acc8
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  phase: Bound
