# Kubeconfig
k3s_kubeconfig: "/etc/rancher/k3s/k3s.yaml"

# Namespace
backup_ns: "sqldump"

# Timezone
marker_tz: "Europe/Paris"

# NFS (Synology)
nfs_server: "192.168.88.5"
nfs_path: "/volume1/k3s-backup"
pv_name: "pv-nfs-syno-backups"
pvc_name: "synology-backups-pvc"
storage_class: "nfs-syno-backups"
pv_capacity: "100Gi"
pvc_request: "50Gi"

# Crony
dump_schedule: "0 3 * * *"         
restorepoint_schedule: "0 * * * *"  
cleanup_schedule: "30 3 * * *"      
smoke_schedule: "0 4 * * *"
rbac_export_schedule: "5 4 * * MON"
keep_last_dumps: 7                  
keep_last_markers: 6


# Nazwy zasobów
dump_cj_name: "neon-dump-nightly"
restore_cj_name: "neon-hourly-marker"
cleanup_cj_name: "cleanup-backups"

# Sekret
secret_name: "neon-secrets"

# Obrazy
img_pg: "postgres:17-alpine"
img_curl: "curlimages/curl:8.8.0"
img_alpine: "alpine:3.20"
