- name: Ensure cloudflared metrics Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: cloudflared-metrics
        namespace: cloudflare
        labels: { app: cloudflared }
      spec:
        selector: { app: cloudflared }
        ports:
          - name: metrics
            port: 2000
            targetPort: 2000
            protocol: TCP

- name: Check if ServiceMonitor CRD exists
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
  register: sm_crd

- name: Ensure ServiceMonitor for cloudflared
  when: sm_crd.resources | length > 0
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: cloudflared
        namespace: monitoring
      spec:
        namespaceSelector:
          matchNames: ["cloudflare"]
        selector:
          matchLabels:
            app: cloudflared
        endpoints:
          - port: metrics
            path: /metrics
            interval: 30s
            scrapeTimeout: 5s
