apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2025-07-22T22:42:09Z"
    labels:
      app.kubernetes.io/component: application-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-application-controller
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.10.7
      helm.sh/chart: argo-cd-6.7.14
    name: argocd-application-controller
    namespace: argocd
    resourceVersion: "17056"
    uid: ff30fff1-2a60-4c3b-b954-51d28b9497d4
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-application-controller
  subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2025-07-22T22:42:09Z"
    labels:
      app.kubernetes.io/component: applicationset-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-applicationset-controller
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.10.7
      helm.sh/chart: argo-cd-6.7.14
    name: argocd-applicationset-controller
    namespace: argocd
    resourceVersion: "17051"
    uid: 8d6ab6b1-f309-44fd-a2cb-328d83ae4104
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-applicationset-controller
  subjects:
  - kind: ServiceAccount
    name: argocd-applicationset-controller
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2025-07-22T22:42:09Z"
    labels:
      app.kubernetes.io/component: dex-server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.10.7
      helm.sh/chart: argo-cd-6.7.14
    name: argocd-dex-server
    namespace: argocd
    resourceVersion: "17052"
    uid: 0bb1a0fc-8f90-48ee-8e73-041676cdbf0a
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-dex-server
  subjects:
  - kind: ServiceAccount
    name: argocd-dex-server
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2025-07-22T22:42:09Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.10.7
      helm.sh/chart: argo-cd-6.7.14
    name: argocd-notifications-controller
    namespace: argocd
    resourceVersion: "17054"
    uid: 1f15e0be-8be9-451a-b2ea-8000a850e330
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-notifications-controller
  subjects:
  - kind: ServiceAccount
    name: argocd-notifications-controller
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2025-07-22T22:42:09Z"
    labels:
      app.kubernetes.io/component: repo-server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-repo-server
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.10.7
      helm.sh/chart: argo-cd-6.7.14
    name: argocd-repo-server
    namespace: argocd
    resourceVersion: "17055"
    uid: f4991054-997a-46ab-a42a-bde2d0e96d35
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-repo-server
  subjects:
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
    creationTimestamp: "2025-07-22T22:42:09Z"
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argocd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: argocd-server
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/version: v2.10.7
      helm.sh/chart: argo-cd-6.7.14
    name: argocd-server
    namespace: argocd
    resourceVersion: "17053"
    uid: 111e9109-6cbb-4cce-a01f-b1d552e51a5c
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: argocd-server
  subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: nfs-subdir-external-provisioner
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2025-07-22T22:37:16Z"
    labels:
      app: nfs-subdir-external-provisioner
      app.kubernetes.io/managed-by: Helm
      chart: nfs-subdir-external-provisioner-4.0.18
      heritage: Helm
      release: nfs-subdir-external-provisioner
    name: leader-locking-nfs-subdir-external-provisioner
    namespace: default
    resourceVersion: "14665"
    uid: d9384e05-1342-476b-8337-a6723ece54c6
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: leader-locking-nfs-subdir-external-provisioner
  subjects:
  - kind: ServiceAccount
    name: nfs-subdir-external-provisioner
    namespace: default
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-07-22T21:21:52Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-public
    resourceVersion: "192"
    uid: d2114a30-d313-48ce-ab0a-a58ca384de66
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:bootstrap-signer
  subjects:
  - kind: ServiceAccount
    name: bootstrap-signer
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4ySv27jMAyHX+XA2fI5sX1xDNxwt3ToFqBdig60xCSqZdKQZPdPkHcvnLRBOyTpKJD88JE/7QB7e08+WGGowTeoUxziVrx9w2iF07YKqZXf4wwSaC0bqGEljv5bNpY3kEBHEQ1GhHoHyCzxMBempzRPpGOgmHorqcYYHU0wO1EgOVuXZyavNmMLNbR5+FIZZ8mvW8vm7z9jhK8iGDuCGrTuftQaetRTfzs0pMJriNTBPgGHDbmLC20xbKGGMquWxZ+qLEpdFtW8mOV6sc5KqvIFLZuqWmdzNFk5n6Afam0elHYyGKWFoxfnyKsOGTfk1ZQEcbT6cFLlCQ15OM6ecfXiaEXrQxi9vfEy9Jdy/R4qnLToJRJPn0JhbwP58azNPoEwHM8C9cPuE3cXTqZXtry0z+P+PQAA//8x+Zq3oQIAAA
      objectset.rio.cattle.io/id: ""
      objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
      objectset.rio.cattle.io/owner-name: ccm
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2025-07-22T21:21:56Z"
    labels:
      objectset.rio.cattle.io/hash: 5089468545c5482413c7f05e837e9b88f02ad052
    name: k3s-cloud-controller-manager-authentication-reader
    namespace: kube-system
    resourceVersion: "262"
    uid: 7bdacfe3-a70e-4980-a66e-639fc7e62545
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: k3s-cloud-controller-manager
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2025-07-22T22:28:10Z"
    name: kube-vip-rolebinding
    namespace: kube-system
    resourceVersion: "11402"
    uid: 924d0e47-f0e1-4de7-8c45-76a181498b91
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kube-vip-role
  subjects:
  - kind: ServiceAccount
    name: kube-vip
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4ySP0/DMBDFvwq6OQmkbaoqEkNZGNiKxIIYLvZreySxI9sJf6p+d+RCUTs0MFqn9/P7+bwj7uQJzos1VJKrWGXch6118slBrMnqhc/EXg85JVSL0VTSyja4E6PFbCihFoE1B6ZyR2yMDYecj0dbvUIFj5A5sZniEBpEmEQKJRfn9s3ApZuhppLqqT+ZDHly9SBG3y61tuZPhOEWVFI0Sh1Yw/0r4jtWMVf3FVL/4QNa2ifUcIVmVGzLfkslFXquoVVV5MjVBJiogteTm1mB2VQviiKv5noxXc8j9Kdii+BE+dTDDXDpeeORTs42WGF9ePxO7p3tu7E9ni+Rfq/He4CJnyDlTk46wARRB8CxzT4h33/rU/m8O+Ie4QZRWCplexPogteYy8v+KwAA///W26sDjQIAAA
      objectset.rio.cattle.io/id: ""
      objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
      objectset.rio.cattle.io/owner-name: auth-reader
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2025-07-22T21:21:56Z"
    labels:
      objectset.rio.cattle.io/hash: 5d6dedcb51e1c2ee2c5af2045e43d8551b6d83f6
    name: metrics-server-auth-reader
    namespace: kube-system
    resourceVersion: "300"
    uid: 4a133222-b49f-4d73-96b3-b7e643a549c9
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-07-22T21:21:52Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::extension-apiserver-authentication-reader
    namespace: kube-system
    resourceVersion: "186"
    uid: 189dc1bf-bd86-4a82-b560-5096bf994bbf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: extension-apiserver-authentication-reader
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-controller-manager
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-scheduler
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-07-22T21:21:52Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-controller-manager
    namespace: kube-system
    resourceVersion: "187"
    uid: 42105382-ae56-4623-a79f-3575e21b146b
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system::leader-locking-kube-controller-manager
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-controller-manager
  - kind: ServiceAccount
    name: kube-controller-manager
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-07-22T21:21:52Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-scheduler
    namespace: kube-system
    resourceVersion: "188"
    uid: 5b9f24da-eabc-4ddd-8338-b7cef7426990
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system::leader-locking-kube-scheduler
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:kube-scheduler
  - kind: ServiceAccount
    name: kube-scheduler
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-07-22T21:21:52Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-system
    resourceVersion: "189"
    uid: 62160381-bfc7-42af-bbb5-dc5fb3b08f52
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:bootstrap-signer
  subjects:
  - kind: ServiceAccount
    name: bootstrap-signer
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-07-22T21:21:52Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:cloud-provider
    namespace: kube-system
    resourceVersion: "190"
    uid: 4f1512a0-7800-4ee1-92b4-7aed173fff38
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:cloud-provider
  subjects:
  - kind: ServiceAccount
    name: cloud-provider
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-07-22T21:21:52Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:token-cleaner
    namespace: kube-system
    resourceVersion: "191"
    uid: 6d1466f3-e82b-4528-b3b7-02e1801a4972
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:controller:token-cleaner
  subjects:
  - kind: ServiceAccount
    name: token-cleaner
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: metallb
      meta.helm.sh/release-namespace: metallb-system
    creationTimestamp: "2025-07-22T22:30:54Z"
    labels:
      app.kubernetes.io/instance: metallb
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: metallb
      app.kubernetes.io/version: v0.15.2
      helm.sh/chart: metallb-0.15.2
    name: metallb-controller
    namespace: metallb-system
    resourceVersion: "12498"
    uid: c80be8db-f081-406e-a7ad-e88022ec94b1
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: metallb-controller
  subjects:
  - kind: ServiceAccount
    name: metallb-controller
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: metallb
      meta.helm.sh/release-namespace: metallb-system
    creationTimestamp: "2025-07-22T22:30:54Z"
    labels:
      app.kubernetes.io/instance: metallb
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: metallb
      app.kubernetes.io/version: v0.15.2
      helm.sh/chart: metallb-0.15.2
    name: metallb-pod-lister
    namespace: metallb-system
    resourceVersion: "12497"
    uid: 52644e66-3728-4efb-936a-545738a7cc20
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: metallb-pod-lister
  subjects:
  - kind: ServiceAccount
    name: metallb-speaker
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: kube-prometheus-stack
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-07-22T22:37:50Z"
    labels:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 12.1.0
      helm.sh/chart: grafana-9.3.0
    name: kube-prometheus-stack-grafana
    namespace: monitoring
    resourceVersion: "1743118"
    uid: ad1a767f-c1fa-4277-9f55-0d7ca4a1b797
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kube-prometheus-stack-grafana
  subjects:
  - kind: ServiceAccount
    name: kube-prometheus-stack-grafana
    namespace: monitoring
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2025-08-09T20:21:11Z"
    name: rbac-readonly-bind
    namespace: sqldump
    resourceVersion: "8004844"
    uid: 0eb31d0f-1f60-49ba-90c8-b03c0228e0ae
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rbac-readonly
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: sqldump
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: velero
      meta.helm.sh/release-namespace: velero
    creationTimestamp: "2025-07-26T19:15:39Z"
    labels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: velero
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: velero
      helm.sh/chart: velero-5.2.0
    name: velero-server
    namespace: velero
    resourceVersion: "1760840"
    uid: 518f6221-56b4-4a6f-97be-65b2a9d08da1
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: velero-server
  subjects:
  - kind: ServiceAccount
    name: velero-server
    namespace: velero
kind: List
metadata:
  resourceVersion: ""
