---

- name: Configure SSH hardening
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: 'sshd -t -f %s'
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin prohibit-password' }
    - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
  notify: Restart sshd
  when: ssh_hardening | bool
  

- name: 1. Install fail2ban package
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: 2. Deploy fail2ban local configuration
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: 3. Enable and start fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    enabled: yes
    state: started

- name: 4. Configure passwordless sudo for 'devistor' user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/devistor
    line: "devistor ALL=(ALL) NOPASSWD: ALL"
    state: present
    create: yes
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -csf %s