---
###############################################################################
# Worker node — download installer
###############################################################################

- name: Download installation script on worker node
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /usr/local/bin/k3s_install.sh
    mode: '0755'

###############################################################################
# Install K3s agent
###############################################################################

- name: Install agent
  ansible.builtin.shell: |
    INSTALL_K3S_VERSION="{{ k3s_version }}"; \
    K3S_URL="https://{{ vip_address }}:6443"; \
    K3S_TOKEN="{{ hostvars[groups['k3s_masters'][0]].k3s_token }}"; \
    /usr/local/bin/k3s_install.sh
  args:
    creates: /etc/systemd/system/k3s-agent.service
  notify: restart k3s

###############################################################################
# Label worker nodes
###############################################################################

- name: Label workers with role=worker
  ansible.builtin.shell: |
    kubectl label node {{ item }} role=worker --overwrite
  loop:
    - k8s-worker-01
    - k8s-worker-02
    - k8s-worker-03
  delegate_to: localhost
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig }}"
  run_once: true
