- name: Uruchom master.yml jeśli host należy do k3s_masters
  include_tasks: master.yml
  when: "'k3s_masters' in group_names"

- name: Uruchom agent.yml jeśli host należy do k3s_workers
  include_tasks: agent.yml
  when: "'k3s_workers' in group_names"

- name: Ensure /etc/rancher/k3s exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Render /etc/rancher/k3s/config.yaml
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify:
    - restart k3s

- name: Wait for service restart (give K3s time)
  ansible.builtin.pause:
    seconds: 12

- name: Verify control-plane metrics on masters (10257/10259 open to cluster)
  ansible.builtin.shell: |
    ss -tuln | grep -E '(\*:10257|0\.0\.0\.0:10257|\[::\]:10257)' \
      && ss -tuln | grep -E '(\*:10259|0\.0\.0\.0:10259|\[::\]:10259)'
  register: verify_cp
  changed_when: false
  failed_when: verify_cp.rc != 0
  when: inventory_hostname in groups['k3s_masters']

- name: Verify kube-proxy metrics (10249) on all nodes
  ansible.builtin.shell: |
    ss -tuln | grep -E '(\*:10249|0\.0\.0\.0:10249|\[::\]:10249)'
  register: verify_proxy
  changed_when: false
  failed_when: verify_proxy.rc != 0

