---
###############################################################################
# K3s — install on all masters
###############################################################################

- name: Install pip3 and kubernetes library on all masters
  become: true
  tags: [k3s, deps]
  block:
    - name: Ensure pip3, setuptools and venv are installed
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - python3-venv
        state: present
        update_cache: true

    - name: Install kubernetes >= 24.2.0 (required by Ansible)
      pip:
        name: "kubernetes>=24.2.0"
        executable: pip3
        extra_args: "--break-system-packages"

###############################################################################
# Download installer
###############################################################################

- name: Download installation script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /usr/local/bin/k3s_install.sh
    mode: '0755'

###############################################################################
# Primary master flag
###############################################################################

- name: Set a flag for which host is the first master
  ansible.builtin.set_fact:
    is_primary: "{{ inventory_hostname == groups['k3s_masters'][0] }}"

###############################################################################
# Install first master (etcd initializer)
###############################################################################

- name: Install the first master (etcd)
  ansible.builtin.shell: |
    INSTALL_K3S_VERSION="{{ k3s_version }}" \
    INSTALL_K3S_EXEC="server --cluster-init \
      --tls-san {{ vip_address }} --disable traefik --disable servicelb" \
    /usr/local/bin/k3s_install.sh
  when: is_primary
  args:
    creates: /etc/systemd/system/k3s.service
  notify: restart k3s

###############################################################################
# kube-vip on master01
###############################################################################

- name: Copy kube-vip.yaml to master01
  ansible.builtin.copy:
    src: "{{ role_path }}/files/kube-vip.yaml"
    dest: "/tmp/kube-vip.yaml"
  when: is_primary

- name: Apply kube-vip manifest on master01
  kubernetes.core.k8s:
    kubeconfig: "{{ k3s_custom_kubeconfig_path }}"
    src: "/tmp/kube-vip.yaml"
  when: is_primary

###############################################################################
# Wait for API on VIP
###############################################################################

- name: Wait until the API server at the VIP address is available
  ansible.builtin.wait_for:
    host: "{{ vip_address }}"
    port: 6443
    delay: 10         # Wait 15s before the first attempt
    timeout: 60       # Wait up to 5 minutes
    msg: "Waiting for API server to start at {{ vip_address }}:6443"
  run_once: true          # Perform this check only once for the whole group
  delegate_to: localhost  # Check from the Ansible control machine
  become: false 

###############################################################################
# Cluster token (read & share)
###############################################################################

- name: Read cluster token from the first master
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  register: _token
  when: is_primary
  changed_when: false

- name: Save and share cluster token to all hosts
  ansible.builtin.set_fact:
    k3s_token: "{{ hostvars[groups['k3s_masters'][0]]._token.stdout }}"

###############################################################################
# Join remaining masters
###############################################################################

- name: Join the remaining master-nodes
  ansible.builtin.shell: |
    INSTALL_K3S_VERSION="{{ k3s_version }}" \
    INSTALL_K3S_EXEC="server \
      --server https://{{ vip_address }}:6443 \
      --token {{ k3s_token }} --tls-san {{ vip_address }} \
      --disable traefik --disable servicelb" \
    /usr/local/bin/k3s_install.sh
  when: not is_primary
  args:
    creates: /etc/systemd/system/k3s.service
  notify: restart k3s

###############################################################################
# kubeconfig: slurp, patch, and save locally
###############################################################################

- name: Load kubeconfig file content into memory (slurp)
  ansible.builtin.slurp:
    src: "{{ k3s_custom_kubeconfig_path }}" # Reads /etc/rancher/k3s/k3s.yaml
  register: kubeconfig_b64_content
  when: is_primary

# This task block runs only on the first master, which is correct.
# It ensures proper retrieval, modification, and saving of kubeconfig.
- name: Fix and save kubeconfig on the local machine
  when: is_primary
  block:

    - name: Decode and fix server address in kubeconfig
      ansible.builtin.set_fact:
        # Decode base64 content and replace server address right away
        modified_kubeconfig: "{{ kubeconfig_b64_content['content'] | b64decode | replace('127.0.0.1', vip_address) }}"

    - name: Write the final, corrected kubeconfig to a local file
      ansible.builtin.copy:
        content: "{{ modified_kubeconfig }}"
        dest: "{{ k3s_kubeconfig }}" # Writes to /home/test/.kube/config-k3s
        mode: '0600'
      # IMPORTANT: Run this task on localhost, as a regular user
      delegate_to: localhost
      become: false
