---
- name: "01: Apply central services policies (Traefik)"
  ansible.builtin.include_tasks: 01_central_services.yml

- name: "02: Apply application policies (dev/prod)"
  ansible.builtin.include_tasks: 02_applications.yml

- name: "03: Apply Traefik egress policies"
  ansible.builtin.include_tasks: 03_traefik_egress.yml

- name: "04: Apply Argo CD policies"
  ansible.builtin.include_tasks: 04_argocd.yml

- name: "05: Apply monitoring stack policies (Prometheus, Grafana, etc.)"
  ansible.builtin.include_tasks: 05_monitoring_stack.yml

- name: "06: Apply Cloudflare policies"
  ansible.builtin.include_tasks: 06_cloudflare.yml
